Translation.addTranslation("Leadstone Solar Panel", {ru:"Свинцовая Солнечная Панель"});
Translation.addTranslation("Hardent Solar Panel", {ru:"Закалённая Солнечная Панель"});
Translation.addTranslation("Redstone Solar Panel", {ru:"Краснокаменная Солнечная Панель"});
Translation.addTranslation("Resonant Solar Panel", {ru:"Резонирующая Солнечная Панель"});
Translation.addTranslation("Advanced Solar Panel", {ru:"Улучшенная Солнечная Панель"});
Translation.addTranslation("Ultimate Solar Panel", {ru:"Идеальная Солнечная Панель"});
Translation.addTranslation("Power tier", {ru: "Энергоуровень"});
Translation.addTranslation("§5Maksim Kievsky: §2detected a problem with a block drop. §114.02.2018 §9version 2.0.1", {ru: "§5Максим Киевский: §2обнаружил проблему с дропом блоков. §114.02.2018 §9версии 2.0.1"});
Translation.addTranslation("§5miron27khv: §4created 90% of texture mod. §9Was taken to the development team since version 2.2.3", {ru: "§5miron27khv: §создал 90% текстур мода. §9состоит в команде разработчиков с версии 2.2.3"});
Translation.addTranslation("§4ripemc: §6 noticed a bug with integration with IC². §214.04.2019 §9version 2.4.5.3", {ru: "§4ripemc: §6 заметил баг с интеграцией с IC². §214.04.2019 §9версии 2.4.5.3"});
Translation.addTranslation("§5BrassyFaNToM: §7 reported an error with most of the mechanisms. §C08.06.2019 §9 Versions §b3§f.§70", {ru: "§5BrassyFaNToM: §7 сообщил о баге с большинством механизмов. §C08.06.2019 §9версии §b3§f.§80"});
Translation.addTranslation("This message can be disabled by disabling the show_helpers_message parameter in the config (games/com.mojang/mods/ores/config.json)", {ru: "это сообщение можно отключить, отключив параметр show_helpers_message в конфиге (games/com.mojang/mods/ores/config.json)"});
Translation.addTranslation("All about Ores Mod", {ru: "Все о моде Ores Mod"});
Translation.addTranslation("About ores", {ru: "О рудах"});
Translation.addTranslation("About mechanical blocks", {ru: "О механических блоках"});
Translation.addTranslation("About other items", {ru: "О прочих предметах"});
Translation.addTranslation("To main", {ru: "На главную"});
Translation.addTranslation("To the list", {ru: "К списку"});
Translation.addTranslation("Used in crafts.", {ru: "Используется в крафтах."});
Translation.addTranslation("Advantage", {ru: "Преимущество"});
Translation.addTranslation("Disadvantage", {ru: "Недостаток"});
Translation.addTranslation("not rare", {ru: "не редкий"});
Translation.addTranslation("no strengths", {ru: "нет сильных сторон"});
Translation.addTranslation("Adamantite", {ru: "Адамантит"});
Translation.addTranslation("Lead", {ru: "Свинец"});
Translation.addTranslation("Malachite", {ru: "Малахит"});
Translation.addTranslation("Muthril", {ru: "Мифрил"});
Translation.addTranslation("Uranium", {ru: "Ураниум"});
Translation.addTranslation("Sapphire", {ru: "Сапфир"});
Translation.addTranslation("very fast", {ru: "Очень быстрый"});
Translation.addTranslation("not durable", {ru: "Не долговечен"});
Translation.addTranslation("strength", {ru: "сильный"});
Translation.addTranslation("low speed", {ru: "низкая скорость"});
Translation.addTranslation("the most effective material", {ru: "самый эффективный материал"});
Translation.addTranslation("rate", {ru: "редкий"});
Translation.addTranslation("effective, has the highest damage", {ru: "эффективный, имеет самый высокий урон"});
Translation.addTranslation("rarely comes across", {ru: "редко попадается"});
Translation.addTranslation("Turns reconstructed matter into objects.", {ru: "Превращает реконструированную материю в предметы."});
Translation.addTranslation("Using molecular converter", {ru: "Использование молекулярного конвертатора"});
Translation.addTranslation("The information panel in the mechanism window displays the current state of the mechanism and helps to understand how the mechanism works.", {ru: "Информационная панель в окне механизма отображает текущее состояние механизма и помогает понять, как работает механизм."});
Translation.addTranslation("As a result, you will receive an item that was as a result of the reconstruction of matter.", {ru: "В результате вы получите предмет, который был в результате реконструкции материи."});
Translation.addTranslation("At the exit you will receive the item that was recorded in the reconstructed matter.", {ru: "На выходе вы получите предмет, который был записан в реконструированной материи."});
Translation.addTranslation("The only source of chips", {ru: "Единственный источник получения чипов"});
Translation.addTranslation("Using a laboratory block", {ru: "Использование лабораторного блока."});
Translation.addTranslation("For the mechanism to work, you need to: keep the mechanism charged with energy and place the research chips in the upper slot.", {ru: "Чтобы механизм работал, вам необходимо: держать механизм заряженным энергией и поместить исследовательские чипы в верхний слот."});
Translation.addTranslation("Generator, for generating a new type of energy QE (Quantum Energy)", {ru: "Генератор, для генерации нового типа энергии QE(Quantum Energy)"});
Translation.addTranslation("Using a molecular generator", {ru: "Использование молекулярного генератора"});
Translation.addTranslation("Working with this mechanism is the easiest.", {ru: "Работа с этим механизмом самая простая."});
Translation.addTranslation("In the interface of the mechanism there are many slots, in these slots are placed any items that the mechanism will turn into energy.", {ru: "В интерфейсе механизма находится множество слотов, в эти слоты помещаются любые предметы, которые механизм превратит в энергию."});
Translation.addTranslation("The mechanism does not consume Eu-energy.", {ru: "Механизм не потребляет Eu-энергии."});
Translation.addTranslation("The removal of energy is carried out by attaching a special conductor to the upper side of the mechanism.", {ru: "Вывод энергии осуществляется, путем присоединения специального проводника к верхней стороне механизма."});
Translation.addTranslation("He accepts ordinary matter and any object, the data of which he will transmit to matter and will issue reconstructed matter.", {ru: "Принимает обычную материю и какой-либо предмет, данные которого он передаст в материю и выдаст реконструированную материю."});
Translation.addTranslation("Reconstructed matter is used in a molecular transducer.", {ru: "Реконструированная материя применяется в молекулярном преобразователе."});
Translation.addTranslation("Use of matter re-constructor", {ru: "Использование реконструктора материи"});
Translation.addTranslation("To understand the mechanism, just open it and look at the panel below.", {ru: "Чтобы понять, как работает механизм, посмотрите на панель снизу, в окне механизма."});
Translation.addTranslation("The red and yellow text indicates that the mechanism is lacking for work.", {ru: "Красный и желтый текст показывают, что нехватает механизму для работы."});
Translation.addTranslation("Molecular compactor compresses QE energy, turning it into matter.", {ru: "Молекулярный уплотнитель сжимает QE энергию, превращая её в материю."});
Translation.addTranslation("The use of molecular sealer.", {ru: "Использование молекулярного уплотнителя."});
Translation.addTranslation("The operation of this mechanism is fully automatic, you just need to maintain working conditions.", {ru: "Работа этого механизма полностью автоматическая, вам лишь нужно поддерживать условия работы"});
Translation.addTranslation("In order for the mechanism to accept QE-energy, you need to connect a wire to it to the upper side.", {ru: "Чтобы механизм принимал QE-энергию - нужно подключить к нему провод к верхней стороне."});
Translation.addTranslation("The mechanism itself begins to work when the energy inside it is greater than 0.", {ru: "Механизм сам начинает работать, когда энергия внутри него больше чем 0."});
Translation.addTranslation("The redstone signal stops the operation of the mechanism, but at the same time it will still be able to absorb energy.", {ru: "Редстоун-сигнал останавливает работу механизма, но при этом он по прежнему сможет принимать в себя энергию."});
Translation.addTranslation("Generation", {ru: "Генерация"});
Translation.addTranslation("night", {ru: "ночью"});
Translation.addTranslation("Leadstone", {ru: "Свинцовая"});
Translation.addTranslation("Hardent", {ru: "Закалённая"});
Translation.addTranslation("Redstone", {ru: "Краснокаменная"});
Translation.addTranslation("Resonant", {ru: "Резонирующая"});
Translation.addTranslation("Advanced", {ru: "Улучшенная"});
Translation.addTranslation("Ultimate", {ru: "Окончательная"});
Translation.addTranslation("This mechanism will grow the tree anywhere.", {ru: "Этот механизм вырастит дерево где угодно."});
Translation.addTranslation("To the instructions", {ru: "К инструкции"});
Translation.addTranslation("Use of a wood incubator", {ru: "Использование древесного инкубатора"});
Translation.addTranslation("To use a wood incubator you will need: seedling, energy and catalyst.", {ru: "Для использования древесного инкубатора понадобится: саженец, энергия и катализатор."});
Translation.addTranslation("List of supported seedlings and catalysts on the right page.", {ru: "Список поддерживаемых саженцев и катализаторов на правой странице."});
Translation.addTranslation("Before using the mechanism, you need to place a block of earth or dirt next to it.", {ru: "Перед использованием механизма вам нужно поставить рядом с ним блок земли или грязи."});
Translation.addTranslation("In the window of the mechanism, approximately in the middle, there is a red rectangle.", {ru: "В окне механизма, примерно по середине, находится красный прямоугольник."});
Translation.addTranslation("You need to work only with slots from the left of this rectangle.", {ru: "Вам нужно работать только со слотами с лева от этого прямоугольника."});
Translation.addTranslation("A sapling is placed in the top slot; in the right - the catalyst", {ru: "В верхний слот помещается саженец; в правый - катализатор"});
Translation.addTranslation("If you did everything correctly, then a sapling will appear on the dirt block, and the red rectangle will turn green.", {ru: "Если вы все сделали правильно - то на блоке грязи появится саженец, а красный прямоугольник будет становиться зелёным."});
Translation.addTranslation("I remind you that the mechanism consumes energy, nothing will work without it.", {ru: "Напоминаю, что механизм потребляет энергию, без неё ничего работать не будет."});
Translation.addTranslation("The red box is the growth progress bar. When progress is completed - you will receive a tree, seedlings and a special drop, if there is one.", {ru: "Красный прямоугольник - шкала прогресса роста. Когда прогресс завершится - вы получите дерево, саженцы и особый дроп, если таков есть."});
Translation.addTranslation("Saplings:", {ru: "Саженцы:"});
Translation.addTranslation("Currently supported saplings from Minecraft and Industrial Craft", {ru: "В настоящий момент поддерживаются cаженцы из Minecraft и Industrial Craft"});
Translation.addTranslation("Catalysts:", {ru: "Катализаторы:"});
Translation.addTranslation("Bone flour.", {ru: "Костная мука."});
Translation.addTranslation("The catalyst is used to accelerate the growth of the tree, its use is not necessary", {ru: "Катализатор используется для ускорения роста дерева, его использование не обязательно"});
Translation.addTranslation("Solar Panels", {ru: "Солнечная панель"});
Translation.addTranslation("Chips", {ru: "Чипы"});
Translation.addTranslation("Receiving:", {ru: "Получение:"});
Translation.addTranslation("Application:", {ru: "Применение:"});
Translation.addTranslation("Creating mechanisms", {ru: "Создание механизмов"});
Translation.addTranslation("Used in the creation of solar panels", {ru: "Используются в создании солнечных панелей"});
Translation.addTranslation("To find out the recipe for higher level kernels, put the core one level less in inventory and open the inventory.", {ru: "Чтобы узнать рецепт ядер более высокого уровня - положите в инвентарь ядро на один уровень меньше и откройте инвентарь."});
Translation.addTranslation("For example, to find out the recipe for the core of a hardened solar panel - take the lead core and open the workbench.", {ru: "Например, чтобы узнать рецепт для ядра закаленной солнечной панели - возьмите ядро свинцовой и откройте верстак."});
Translation.addTranslation("Cores", {ru: "Ядра"});
Translation.addTranslation("Nuggets", {ru: "Самородки"});
Translation.addTranslation("Nanite Collector", {ru: "Сборщик Нанитов"});
Translation.addTranslation("Nanite Training Node", {ru: "Узел Обучения Нанитов"});
Translation.addTranslation("Input", {ru: "Выход"});
Translation.addTranslation("Most of the nuggets are obtained from the same name full-fledged ingots (in the case of a lapis lazuli fragment - this is a whole lapis lazuli), except for unidentified and electroumovogo nuggets", {ru: "Большая часть самородков получена из одноименных полноценных слитков (в случае с фрагментом ляпис-лазури-это целый ляпис-лазурь), за исключением неидентифицированных и электроумовых самородков"});
Translation.addTranslation("To back", {ru: "Назад"});
Translation.addTranslation("Rebuilt Matter", {ru: "Реконструированная Материя"});
Translation.addTranslation("The same mechanism that will modify your mechanical armor", {ru: "Тот самый механизм, что будет модифицировать вашу механическую броню"});
Translation.addTranslation("The use of Desk trainer armor", {ru: "Использование стола имплантирования брони"});
Translation.addTranslation("When you open the mechanism window, you will see two slots.", {ru: "При открытии окна механизма, будет видно два слота."});
Translation.addTranslation("Only a flask with trained nanites is installed in the upper slot", {ru: "В верхний слот устанавливается только колба с обученными нанитами"});
Translation.addTranslation("only mechanical armor is installed in the center slot.", {ru: "в центральный слот устанавливается только механическая броня."});
Translation.addTranslation("after installing the mechanical armor in the slot, a certain number of new slots will appear, these are conditional cells of modifications.", {ru: "после установки механической брони в слот, появится некоторое количество новых слотов, это условные ячейки модификаций."});
Translation.addTranslation("clicking on the conditional modification slots will show you their status in the form of text information, if the slot is blocked - it needs to be unlocked by the nanites of the \"Builder\" specialization before the modification can be implemented in it.", {ru: "нажатие на условные слоты модификации покажет вам их статус в виде текстовой информации, если слот заблокирован - он должен быть разблокирован нанитами специализации \"Строитель\", прежде чем модификация может быть реализована в нем."});
Translation.addTranslation("all implemented modifications cannot be extracted or replaced, only improved by re-introducing nanites of the same specialization.", {ru: "все внедрённые модификации не могут быть извлечены или заменены, только улучшены, путём повторного внедрения нанитов той же специализации."});
Translation.addTranslation("Father of mechanical micro-organisms", {ru: "Отец механических микроорганизмов"});
Translation.addTranslation("There are three slots in the mechanism next to each other", {ru: "В механизме находятся три рядом находящихся слота"});
Translation.addTranslation("The left slot is intended for iron ingots", {ru: "Левый слот предназначен для железных слитков"});
Translation.addTranslation("Central for empty flasks", {ru: "Центральный для пустых колб"});
Translation.addTranslation("Right for red dust", {ru: "Правый для красной пыли"});
Translation.addTranslation("The mechanism needs two types of energy to start producing nanites", {ru: "Механизму нужно два типа энергии, чтобы начать производство нанитов"});
Translation.addTranslation("Once production is complete you will receive one nanite capsule", {ru: "После завершения производства вы получите одну капсулу с нанитами"});
Translation.addTranslation("Using the nanite collector", {ru: "Использованме сборщика нанитов"});
Translation.addTranslation("Nanites also need to learn", {ru: "Нанитам тоже нужно учиться"});
Translation.addTranslation("Using the nanite training node", {ru: "Использование узла обучения нанитов"});
Translation.addTranslation("You need to select the desired specification of nanites, and then place the flask with nanites in the left slot. The mechanism will issue a flask with trained nanites", {ru: "Вам нужно выбрать нужную вам спецификацию нанитов, после чего поместить колбу с нанитами в левый слот. Механизм выдаст колбу с обученными нанитами"});
Translation.addTranslation("Only he is able to charge a mechanical armor", {ru: "Только он способен зарядить механическую броню"});
Translation.addTranslation("Well there's nothing to explain ｡ ◕ ‿ ◕ ｡", {ru: "Ну тут объяснять нечего ｡ ◕ ‿ ◕ ｡"});
Translation.addTranslation("Nanites", {ru: "Наниты"});
Translation.addTranslation("Craft of glass on the workbench", {ru: "Крафт из стекла на верстаке"});
Translation.addTranslation("Components of mechanical armor", {ru: "Компоненты механической брони"});
Translation.addTranslation("Mechanic Armor", {ru: "Механическая Броня"});
Translation.addTranslation("Adamantite mechanical armor", {ru: "Адамантитовая механическая броня"});
Translation.addTranslation("Sapphire mechanical armor", {ru: "Сапфировая механическая броня"});
Translation.addTranslation("By itself, this armor has nothing special.", {ru: "Сама по себе эта броня не имеет ничего особенного."});
Translation.addTranslation("This armor can be embedded with nanites on the armor implantation table.", {ru: "В эту броню возможно внедрение нанитов на столе имплантирования брони."});
Translation.addTranslation("Embedding nanites will give you the property that the selected type of nanites is designed for when training in the nanite learning node", {ru: "Внедрение нанитов даст вам то свойство, на который рассчитан выбранный вами тип нанитов при обучении в узле обучения нанитов"});
Translation.addTranslation("Armor modifications", {ru: "Модификации брони"});
Translation.addTranslation("All existing modifications of mechanical armor are listed below. They are needed to improve it", {ru: "Ниже перечислены все существующие модификации механической брони. Они нужны для её улучшения"});
Translation.addTranslation("Builder", {ru: "Строитель"});
Translation.addTranslation("Power", {ru: "Сила"});
Translation.addTranslation("Refractoriness", {ru: "Огнеупорность"});
Translation.addTranslation("Protection from damage", {ru: "Защита от порчи"});
Translation.addTranslation("Power panel", {ru: "Силовой щит"});
Translation.addTranslation("Night vision", {ru: "Ночное зрение"});
Translation.addTranslation("Reinforced hull", {ru: "Укреплённый корпус"});
Translation.addTranslation("The speed of digging", {ru: "Скорость копания"});
Translation.addTranslation("Acceleration", {ru: "Ускорение"});
Translation.addTranslation("Compressed Cargo Space", {ru: "Сжатое Грузовое Пространство"});
Translation.addTranslation("Submariner", {ru: "Подводник"});
Translation.addTranslation("Integrated jetpack", {ru: "Интегрированный реактивный ранец"});
Translation.addTranslation("Anti-gravity field generator", {ru: "Генератор антигравитационного поля"});
Translation.addTranslation("Defense module", {ru: "Модуль обороны"});
Translation.addTranslation("This modification is designed to unlock modification slots.", {ru: "Эта модификация предназначена для разблокировки слотов модификаций."});
Translation.addTranslation("This modification will cause additional damage to the enemy", {ru: "Эта модификация будет наносить дополнительный урон противнику"});
Translation.addTranslation("It is installed in the bib", {ru: "Устанавливается в нагрудник"});
Translation.addTranslation("In constant mode, it provides protection from everything that is hot", {ru: "В постоянном режиме обеспечивает защиту от всего, что горячее"});
Translation.addTranslation("    At the first level it protects against blindness and food poisoning", {ru: "    На первом уровне защищает от слепоты и пищевого отравления"});
Translation.addTranslation("    At the second level, it neutralizes slowing down, nausea and weakness", {ru: "   На втором уровне нейтрализует замедление, тошноту и слабость"});
Translation.addTranslation("    At the last level it protects against poisoning and desiccation", {ru: "   На последнем уровне защищает от отравления и иссушения"});
Translation.addTranslation("In constant mode provides additional health", {ru: "В постоянном режиме обеспечивает дополнительным здоровьем"});
Translation.addTranslation("Automatically provides perfect visibility in the dark", {ru: "Автоматически обеспечивает идеальную видимость в темноте"});
Translation.addTranslation("Installed in the helmet" , {ru: "Устанавливается в шлем"});
Translation.addTranslation("Absorbs part of the received damage", {ru: "Поглощает часть полученного урона"});
Translation.addTranslation("Deals retaliatory damage to creatures attacking you", {ru: "Наносит ответный урон атакующим вас существам"});
Translation.addTranslation("Automatically activated when blocks are broken", {ru: "Автоматически активируется при ломании блоков"});
Translation.addTranslation("Increases the speed of movement when running", {ru: "Увеличивает скорость передвижения при беге"});
Translation.addTranslation("Installed in greaves", {ru: "Устанавливается в поножи"});
Translation.addTranslation("Provides a storage of items that is always nearby.", {ru: "Обеспечивает хранилище предметов, которое всегда рядом."});
Translation.addTranslation("Increasing the level increases the cargo space capacity", {ru: "Повышение уровня увеличивает ёмкость грузового пространства"});
Translation.addTranslation("You can't drown yourself", {ru: "Утопиться не выйдет"});
Translation.addTranslation("Well, sometimes you can take content from Industrial Craft", {ru: "Ну иногда, можно и взять контент из Industrial Craft"});
Translation.addTranslation("Fly - so fly!", {ru: "Летать - так летать!"});
Translation.addTranslation("Installed in shoes", {ru: "Устанавливается в ботинки"});
Translation.addTranslation("Improved version of mechanical armor.", {ru: "Улучшенный вариант механической брони."});
Translation.addTranslation("When creating a sapphire armor, it will pass all the modifiers that are in the Adamantite armor", {ru: "При создании сапфировой брони, в неё передадуться все модификаторы, которые находятся в адамантитовой броне"});
Translation.addTranslation("Charge", {ru: "Заряд"});
Translation.addTranslation("There should be a research chip in the slot on top", {ru: "В слоте сверху должна быть исследовательская микросхема"});
Translation.addTranslation("Idles", {ru: "Простаивает"});
Translation.addTranslation("No power", {ru: "Нет энергии"});
Translation.addTranslation("The slot on top is not a research chip", {ru: "В слоте сверху находится не исследовательская микросхема"});
Translation.addTranslation("Works", {ru: "Работает"});
Translation.addTranslation("The slot must have an item on top", {ru: "В слоте сверху должен быть предмет"});
Translation.addTranslation("The slot on the left should contain matter", {ru: "В слоте слева должна быть материя"});
Translation.addTranslation("But it is not matter._.", {ru: "Но это не материя._."});
Translation.addTranslation("The slot on the left should contain matter", {ru: "В слоте слева должна быть материя"});
Translation.addTranslation("No matter!!!", {ru: "Материю низя!!!"});
Translation.addTranslation("In the slot above there should be reconstructed matter", {ru: "В слоте сверху должна быть реконструированная материя"});
Translation.addTranslation("The slot on the left should contain matter", {ru: "В слоте слева должна быть материя"});
Translation.addTranslation("Generation", {ru: "Генерация"});
Translation.addTranslation("Condition", {ru: "Состояние"});
Translation.addTranslation("§§1 Vitya Beley: §7 participated in improving recipes for mechanical armor components and creating new resources. §c09.08.2020 §b3§f.§70§f.§36", {ru: "§1Витя Белей: §7проявил соучастие в совершенствовании рецептов компонентов механической брони и созданию новых ресурсов. §c09.08.2020 §b3§f.§70§f.§36"});
